package com.rnexchange.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class BrokerDeskAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBrokerDeskAllPropertiesEquals(BrokerDesk expected, BrokerDesk actual) {
        assertBrokerDeskAutoGeneratedPropertiesEquals(expected, actual);
        assertBrokerDeskAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBrokerDeskAllUpdatablePropertiesEquals(BrokerDesk expected, BrokerDesk actual) {
        assertBrokerDeskUpdatableFieldsEquals(expected, actual);
        assertBrokerDeskUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBrokerDeskAutoGeneratedPropertiesEquals(BrokerDesk expected, BrokerDesk actual) {
        assertThat(actual)
            .as("Verify BrokerDesk auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBrokerDeskUpdatableFieldsEquals(BrokerDesk expected, BrokerDesk actual) {
        assertThat(actual)
            .as("Verify BrokerDesk relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBrokerDeskUpdatableRelationshipsEquals(BrokerDesk expected, BrokerDesk actual) {
        assertThat(actual)
            .as("Verify BrokerDesk relationships")
            .satisfies(a -> assertThat(a.getBroker()).as("check broker").isEqualTo(expected.getBroker()));
    }
}
