package com.rnexchange.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class BrokerAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBrokerAllPropertiesEquals(Broker expected, Broker actual) {
        assertBrokerAutoGeneratedPropertiesEquals(expected, actual);
        assertBrokerAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBrokerAllUpdatablePropertiesEquals(Broker expected, Broker actual) {
        assertBrokerUpdatableFieldsEquals(expected, actual);
        assertBrokerUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBrokerAutoGeneratedPropertiesEquals(Broker expected, Broker actual) {
        assertThat(actual)
            .as("Verify Broker auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBrokerUpdatableFieldsEquals(Broker expected, Broker actual) {
        assertThat(actual)
            .as("Verify Broker relevant properties")
            .satisfies(a -> assertThat(a.getCode()).as("check code").isEqualTo(expected.getCode()))
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBrokerUpdatableRelationshipsEquals(Broker expected, Broker actual) {
        assertThat(actual)
            .as("Verify Broker relationships")
            .satisfies(a -> assertThat(a.getExchange()).as("check exchange").isEqualTo(expected.getExchange()));
    }
}
