package com.rnexchange.domain;

import static com.rnexchange.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class ContractAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertContractAllPropertiesEquals(Contract expected, Contract actual) {
        assertContractAutoGeneratedPropertiesEquals(expected, actual);
        assertContractAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertContractAllUpdatablePropertiesEquals(Contract expected, Contract actual) {
        assertContractUpdatableFieldsEquals(expected, actual);
        assertContractUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertContractAutoGeneratedPropertiesEquals(Contract expected, Contract actual) {
        assertThat(actual)
            .as("Verify Contract auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertContractUpdatableFieldsEquals(Contract expected, Contract actual) {
        assertThat(actual)
            .as("Verify Contract relevant properties")
            .satisfies(a -> assertThat(a.getInstrumentSymbol()).as("check instrumentSymbol").isEqualTo(expected.getInstrumentSymbol()))
            .satisfies(a -> assertThat(a.getContractType()).as("check contractType").isEqualTo(expected.getContractType()))
            .satisfies(a -> assertThat(a.getExpiry()).as("check expiry").isEqualTo(expected.getExpiry()))
            .satisfies(a ->
                assertThat(a.getStrike()).as("check strike").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getStrike())
            )
            .satisfies(a -> assertThat(a.getOptionType()).as("check optionType").isEqualTo(expected.getOptionType()))
            .satisfies(a -> assertThat(a.getSegment()).as("check segment").isEqualTo(expected.getSegment()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertContractUpdatableRelationshipsEquals(Contract expected, Contract actual) {
        assertThat(actual)
            .as("Verify Contract relationships")
            .satisfies(a -> assertThat(a.getInstrument()).as("check instrument").isEqualTo(expected.getInstrument()));
    }
}
