package com.rnexchange.domain;

import static com.rnexchange.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class CorporateActionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCorporateActionAllPropertiesEquals(CorporateAction expected, CorporateAction actual) {
        assertCorporateActionAutoGeneratedPropertiesEquals(expected, actual);
        assertCorporateActionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCorporateActionAllUpdatablePropertiesEquals(CorporateAction expected, CorporateAction actual) {
        assertCorporateActionUpdatableFieldsEquals(expected, actual);
        assertCorporateActionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCorporateActionAutoGeneratedPropertiesEquals(CorporateAction expected, CorporateAction actual) {
        assertThat(actual)
            .as("Verify CorporateAction auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCorporateActionUpdatableFieldsEquals(CorporateAction expected, CorporateAction actual) {
        assertThat(actual)
            .as("Verify CorporateAction relevant properties")
            .satisfies(a -> assertThat(a.getType()).as("check type").isEqualTo(expected.getType()))
            .satisfies(a -> assertThat(a.getInstrumentSymbol()).as("check instrumentSymbol").isEqualTo(expected.getInstrumentSymbol()))
            .satisfies(a -> assertThat(a.getExDate()).as("check exDate").isEqualTo(expected.getExDate()))
            .satisfies(a -> assertThat(a.getPayDate()).as("check payDate").isEqualTo(expected.getPayDate()))
            .satisfies(a -> assertThat(a.getRatio()).as("check ratio").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getRatio()))
            .satisfies(a ->
                assertThat(a.getCashAmount())
                    .as("check cashAmount")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getCashAmount())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCorporateActionUpdatableRelationshipsEquals(CorporateAction expected, CorporateAction actual) {
        assertThat(actual)
            .as("Verify CorporateAction relationships")
            .satisfies(a -> assertThat(a.getInstrument()).as("check instrument").isEqualTo(expected.getInstrument()));
    }
}
