package com.rnexchange.domain;

import static com.rnexchange.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class DailySettlementPriceAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDailySettlementPriceAllPropertiesEquals(DailySettlementPrice expected, DailySettlementPrice actual) {
        assertDailySettlementPriceAutoGeneratedPropertiesEquals(expected, actual);
        assertDailySettlementPriceAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDailySettlementPriceAllUpdatablePropertiesEquals(DailySettlementPrice expected, DailySettlementPrice actual) {
        assertDailySettlementPriceUpdatableFieldsEquals(expected, actual);
        assertDailySettlementPriceUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDailySettlementPriceAutoGeneratedPropertiesEquals(DailySettlementPrice expected, DailySettlementPrice actual) {
        assertThat(actual)
            .as("Verify DailySettlementPrice auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDailySettlementPriceUpdatableFieldsEquals(DailySettlementPrice expected, DailySettlementPrice actual) {
        assertThat(actual)
            .as("Verify DailySettlementPrice relevant properties")
            .satisfies(a -> assertThat(a.getRefDate()).as("check refDate").isEqualTo(expected.getRefDate()))
            .satisfies(a -> assertThat(a.getInstrumentSymbol()).as("check instrumentSymbol").isEqualTo(expected.getInstrumentSymbol()))
            .satisfies(a ->
                assertThat(a.getSettlePrice())
                    .as("check settlePrice")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getSettlePrice())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDailySettlementPriceUpdatableRelationshipsEquals(DailySettlementPrice expected, DailySettlementPrice actual) {
        assertThat(actual)
            .as("Verify DailySettlementPrice relationships")
            .satisfies(a -> assertThat(a.getInstrument()).as("check instrument").isEqualTo(expected.getInstrument()));
    }
}
