package com.rnexchange.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ExchangeIntegrationAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExchangeIntegrationAllPropertiesEquals(ExchangeIntegration expected, ExchangeIntegration actual) {
        assertExchangeIntegrationAutoGeneratedPropertiesEquals(expected, actual);
        assertExchangeIntegrationAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExchangeIntegrationAllUpdatablePropertiesEquals(ExchangeIntegration expected, ExchangeIntegration actual) {
        assertExchangeIntegrationUpdatableFieldsEquals(expected, actual);
        assertExchangeIntegrationUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExchangeIntegrationAutoGeneratedPropertiesEquals(ExchangeIntegration expected, ExchangeIntegration actual) {
        assertThat(actual)
            .as("Verify ExchangeIntegration auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExchangeIntegrationUpdatableFieldsEquals(ExchangeIntegration expected, ExchangeIntegration actual) {
        assertThat(actual)
            .as("Verify ExchangeIntegration relevant properties")
            .satisfies(a -> assertThat(a.getProvider()).as("check provider").isEqualTo(expected.getProvider()))
            .satisfies(a -> assertThat(a.getApiKey()).as("check apiKey").isEqualTo(expected.getApiKey()))
            .satisfies(a -> assertThat(a.getApiSecret()).as("check apiSecret").isEqualTo(expected.getApiSecret()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getLastHeartbeat()).as("check lastHeartbeat").isEqualTo(expected.getLastHeartbeat()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExchangeIntegrationUpdatableRelationshipsEquals(ExchangeIntegration expected, ExchangeIntegration actual) {
        assertThat(actual)
            .as("Verify ExchangeIntegration relationships")
            .satisfies(a -> assertThat(a.getExchange()).as("check exchange").isEqualTo(expected.getExchange()));
    }
}
