package com.rnexchange.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ExchangeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExchangeAllPropertiesEquals(Exchange expected, Exchange actual) {
        assertExchangeAutoGeneratedPropertiesEquals(expected, actual);
        assertExchangeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExchangeAllUpdatablePropertiesEquals(Exchange expected, Exchange actual) {
        assertExchangeUpdatableFieldsEquals(expected, actual);
        assertExchangeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExchangeAutoGeneratedPropertiesEquals(Exchange expected, Exchange actual) {
        assertThat(actual)
            .as("Verify Exchange auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExchangeUpdatableFieldsEquals(Exchange expected, Exchange actual) {
        assertThat(actual)
            .as("Verify Exchange relevant properties")
            .satisfies(a -> assertThat(a.getCode()).as("check code").isEqualTo(expected.getCode()))
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getTimezone()).as("check timezone").isEqualTo(expected.getTimezone()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExchangeUpdatableRelationshipsEquals(Exchange expected, Exchange actual) {
        // empty method
    }
}
