package com.rnexchange.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ExchangeOperatorAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExchangeOperatorAllPropertiesEquals(ExchangeOperator expected, ExchangeOperator actual) {
        assertExchangeOperatorAutoGeneratedPropertiesEquals(expected, actual);
        assertExchangeOperatorAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExchangeOperatorAllUpdatablePropertiesEquals(ExchangeOperator expected, ExchangeOperator actual) {
        assertExchangeOperatorUpdatableFieldsEquals(expected, actual);
        assertExchangeOperatorUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExchangeOperatorAutoGeneratedPropertiesEquals(ExchangeOperator expected, ExchangeOperator actual) {
        assertThat(actual)
            .as("Verify ExchangeOperator auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExchangeOperatorUpdatableFieldsEquals(ExchangeOperator expected, ExchangeOperator actual) {
        assertThat(actual)
            .as("Verify ExchangeOperator relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExchangeOperatorUpdatableRelationshipsEquals(ExchangeOperator expected, ExchangeOperator actual) {
        assertThat(actual)
            .as("Verify ExchangeOperator relationships")
            .satisfies(a -> assertThat(a.getExchange()).as("check exchange").isEqualTo(expected.getExchange()));
    }
}
