package com.rnexchange.domain;

import static com.rnexchange.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class ExecutionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExecutionAllPropertiesEquals(Execution expected, Execution actual) {
        assertExecutionAutoGeneratedPropertiesEquals(expected, actual);
        assertExecutionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExecutionAllUpdatablePropertiesEquals(Execution expected, Execution actual) {
        assertExecutionUpdatableFieldsEquals(expected, actual);
        assertExecutionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExecutionAutoGeneratedPropertiesEquals(Execution expected, Execution actual) {
        assertThat(actual)
            .as("Verify Execution auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExecutionUpdatableFieldsEquals(Execution expected, Execution actual) {
        assertThat(actual)
            .as("Verify Execution relevant properties")
            .satisfies(a -> assertThat(a.getExecTs()).as("check execTs").isEqualTo(expected.getExecTs()))
            .satisfies(a -> assertThat(a.getPx()).as("check px").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getPx()))
            .satisfies(a -> assertThat(a.getQty()).as("check qty").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getQty()))
            .satisfies(a -> assertThat(a.getLiquidity()).as("check liquidity").isEqualTo(expected.getLiquidity()))
            .satisfies(a -> assertThat(a.getFee()).as("check fee").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getFee()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExecutionUpdatableRelationshipsEquals(Execution expected, Execution actual) {
        assertThat(actual)
            .as("Verify Execution relationships")
            .satisfies(a -> assertThat(a.getOrder()).as("check order").isEqualTo(expected.getOrder()));
    }
}
