package com.rnexchange.domain;

import static com.rnexchange.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class LedgerEntryAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLedgerEntryAllPropertiesEquals(LedgerEntry expected, LedgerEntry actual) {
        assertLedgerEntryAutoGeneratedPropertiesEquals(expected, actual);
        assertLedgerEntryAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLedgerEntryAllUpdatablePropertiesEquals(LedgerEntry expected, LedgerEntry actual) {
        assertLedgerEntryUpdatableFieldsEquals(expected, actual);
        assertLedgerEntryUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLedgerEntryAutoGeneratedPropertiesEquals(LedgerEntry expected, LedgerEntry actual) {
        assertThat(actual)
            .as("Verify LedgerEntry auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLedgerEntryUpdatableFieldsEquals(LedgerEntry expected, LedgerEntry actual) {
        assertThat(actual)
            .as("Verify LedgerEntry relevant properties")
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()))
            .satisfies(a -> assertThat(a.getType()).as("check type").isEqualTo(expected.getType()))
            .satisfies(a ->
                assertThat(a.getAmount()).as("check amount").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getAmount())
            )
            .satisfies(a -> assertThat(a.getFee()).as("check fee").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getFee()))
            .satisfies(a -> assertThat(a.getCcy()).as("check ccy").isEqualTo(expected.getCcy()))
            .satisfies(a ->
                assertThat(a.getBalanceAfter())
                    .as("check balanceAfter")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getBalanceAfter())
            )
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getReference()).as("check reference").isEqualTo(expected.getReference()))
            .satisfies(a -> assertThat(a.getRemarks()).as("check remarks").isEqualTo(expected.getRemarks()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLedgerEntryUpdatableRelationshipsEquals(LedgerEntry expected, LedgerEntry actual) {
        assertThat(actual)
            .as("Verify LedgerEntry relationships")
            .satisfies(a -> assertThat(a.getTradingAccount()).as("check tradingAccount").isEqualTo(expected.getTradingAccount()));
    }
}
