package com.rnexchange.domain;

import static com.rnexchange.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class LotAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLotAllPropertiesEquals(Lot expected, Lot actual) {
        assertLotAutoGeneratedPropertiesEquals(expected, actual);
        assertLotAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLotAllUpdatablePropertiesEquals(Lot expected, Lot actual) {
        assertLotUpdatableFieldsEquals(expected, actual);
        assertLotUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLotAutoGeneratedPropertiesEquals(Lot expected, Lot actual) {
        assertThat(actual)
            .as("Verify Lot auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLotUpdatableFieldsEquals(Lot expected, Lot actual) {
        assertThat(actual)
            .as("Verify Lot relevant properties")
            .satisfies(a -> assertThat(a.getOpenTs()).as("check openTs").isEqualTo(expected.getOpenTs()))
            .satisfies(a ->
                assertThat(a.getOpenPx()).as("check openPx").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getOpenPx())
            )
            .satisfies(a ->
                assertThat(a.getQtyOpen()).as("check qtyOpen").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getQtyOpen())
            )
            .satisfies(a ->
                assertThat(a.getQtyClosed()).as("check qtyClosed").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getQtyClosed())
            )
            .satisfies(a -> assertThat(a.getMethod()).as("check method").isEqualTo(expected.getMethod()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLotUpdatableRelationshipsEquals(Lot expected, Lot actual) {
        assertThat(actual)
            .as("Verify Lot relationships")
            .satisfies(a -> assertThat(a.getPosition()).as("check position").isEqualTo(expected.getPosition()));
    }
}
