package com.rnexchange.domain;

import static com.rnexchange.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class MarginRuleAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMarginRuleAllPropertiesEquals(MarginRule expected, MarginRule actual) {
        assertMarginRuleAutoGeneratedPropertiesEquals(expected, actual);
        assertMarginRuleAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMarginRuleAllUpdatablePropertiesEquals(MarginRule expected, MarginRule actual) {
        assertMarginRuleUpdatableFieldsEquals(expected, actual);
        assertMarginRuleUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMarginRuleAutoGeneratedPropertiesEquals(MarginRule expected, MarginRule actual) {
        assertThat(actual)
            .as("Verify MarginRule auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMarginRuleUpdatableFieldsEquals(MarginRule expected, MarginRule actual) {
        assertThat(actual)
            .as("Verify MarginRule relevant properties")
            .satisfies(a -> assertThat(a.getScope()).as("check scope").isEqualTo(expected.getScope()))
            .satisfies(a ->
                assertThat(a.getInitialPct())
                    .as("check initialPct")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getInitialPct())
            )
            .satisfies(a ->
                assertThat(a.getMaintPct()).as("check maintPct").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getMaintPct())
            )
            .satisfies(a -> assertThat(a.getSpanJson()).as("check spanJson").isEqualTo(expected.getSpanJson()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMarginRuleUpdatableRelationshipsEquals(MarginRule expected, MarginRule actual) {
        assertThat(actual)
            .as("Verify MarginRule relationships")
            .satisfies(a -> assertThat(a.getExchange()).as("check exchange").isEqualTo(expected.getExchange()));
    }
}
