package com.rnexchange.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MarketHolidayAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMarketHolidayAllPropertiesEquals(MarketHoliday expected, MarketHoliday actual) {
        assertMarketHolidayAutoGeneratedPropertiesEquals(expected, actual);
        assertMarketHolidayAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMarketHolidayAllUpdatablePropertiesEquals(MarketHoliday expected, MarketHoliday actual) {
        assertMarketHolidayUpdatableFieldsEquals(expected, actual);
        assertMarketHolidayUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMarketHolidayAutoGeneratedPropertiesEquals(MarketHoliday expected, MarketHoliday actual) {
        assertThat(actual)
            .as("Verify MarketHoliday auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMarketHolidayUpdatableFieldsEquals(MarketHoliday expected, MarketHoliday actual) {
        assertThat(actual)
            .as("Verify MarketHoliday relevant properties")
            .satisfies(a -> assertThat(a.getTradeDate()).as("check tradeDate").isEqualTo(expected.getTradeDate()))
            .satisfies(a -> assertThat(a.getReason()).as("check reason").isEqualTo(expected.getReason()))
            .satisfies(a -> assertThat(a.getIsHoliday()).as("check isHoliday").isEqualTo(expected.getIsHoliday()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMarketHolidayUpdatableRelationshipsEquals(MarketHoliday expected, MarketHoliday actual) {
        assertThat(actual)
            .as("Verify MarketHoliday relationships")
            .satisfies(a -> assertThat(a.getExchange()).as("check exchange").isEqualTo(expected.getExchange()));
    }
}
