package com.rnexchange.domain;

import static com.rnexchange.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class PositionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPositionAllPropertiesEquals(Position expected, Position actual) {
        assertPositionAutoGeneratedPropertiesEquals(expected, actual);
        assertPositionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPositionAllUpdatablePropertiesEquals(Position expected, Position actual) {
        assertPositionUpdatableFieldsEquals(expected, actual);
        assertPositionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPositionAutoGeneratedPropertiesEquals(Position expected, Position actual) {
        assertThat(actual)
            .as("Verify Position auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPositionUpdatableFieldsEquals(Position expected, Position actual) {
        assertThat(actual)
            .as("Verify Position relevant properties")
            .satisfies(a -> assertThat(a.getQty()).as("check qty").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getQty()))
            .satisfies(a ->
                assertThat(a.getAvgCost()).as("check avgCost").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getAvgCost())
            )
            .satisfies(a ->
                assertThat(a.getLastPx()).as("check lastPx").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getLastPx())
            )
            .satisfies(a ->
                assertThat(a.getUnrealizedPnl())
                    .as("check unrealizedPnl")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getUnrealizedPnl())
            )
            .satisfies(a ->
                assertThat(a.getRealizedPnl())
                    .as("check realizedPnl")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getRealizedPnl())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPositionUpdatableRelationshipsEquals(Position expected, Position actual) {
        assertThat(actual)
            .as("Verify Position relationships")
            .satisfies(a -> assertThat(a.getTradingAccount()).as("check tradingAccount").isEqualTo(expected.getTradingAccount()))
            .satisfies(a -> assertThat(a.getInstrument()).as("check instrument").isEqualTo(expected.getInstrument()));
    }
}
