package com.rnexchange.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class RiskAlertAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRiskAlertAllPropertiesEquals(RiskAlert expected, RiskAlert actual) {
        assertRiskAlertAutoGeneratedPropertiesEquals(expected, actual);
        assertRiskAlertAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRiskAlertAllUpdatablePropertiesEquals(RiskAlert expected, RiskAlert actual) {
        assertRiskAlertUpdatableFieldsEquals(expected, actual);
        assertRiskAlertUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRiskAlertAutoGeneratedPropertiesEquals(RiskAlert expected, RiskAlert actual) {
        assertThat(actual)
            .as("Verify RiskAlert auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRiskAlertUpdatableFieldsEquals(RiskAlert expected, RiskAlert actual) {
        assertThat(actual)
            .as("Verify RiskAlert relevant properties")
            .satisfies(a -> assertThat(a.getAlertType()).as("check alertType").isEqualTo(expected.getAlertType()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRiskAlertUpdatableRelationshipsEquals(RiskAlert expected, RiskAlert actual) {
        assertThat(actual)
            .as("Verify RiskAlert relationships")
            .satisfies(a -> assertThat(a.getTradingAccount()).as("check tradingAccount").isEqualTo(expected.getTradingAccount()))
            .satisfies(a -> assertThat(a.getTrader()).as("check trader").isEqualTo(expected.getTrader()));
    }
}
