package com.rnexchange.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SettlementBatchAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSettlementBatchAllPropertiesEquals(SettlementBatch expected, SettlementBatch actual) {
        assertSettlementBatchAutoGeneratedPropertiesEquals(expected, actual);
        assertSettlementBatchAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSettlementBatchAllUpdatablePropertiesEquals(SettlementBatch expected, SettlementBatch actual) {
        assertSettlementBatchUpdatableFieldsEquals(expected, actual);
        assertSettlementBatchUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSettlementBatchAutoGeneratedPropertiesEquals(SettlementBatch expected, SettlementBatch actual) {
        assertThat(actual)
            .as("Verify SettlementBatch auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSettlementBatchUpdatableFieldsEquals(SettlementBatch expected, SettlementBatch actual) {
        assertThat(actual)
            .as("Verify SettlementBatch relevant properties")
            .satisfies(a -> assertThat(a.getRefDate()).as("check refDate").isEqualTo(expected.getRefDate()))
            .satisfies(a -> assertThat(a.getKind()).as("check kind").isEqualTo(expected.getKind()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()))
            .satisfies(a -> assertThat(a.getRemarks()).as("check remarks").isEqualTo(expected.getRemarks()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSettlementBatchUpdatableRelationshipsEquals(SettlementBatch expected, SettlementBatch actual) {
        assertThat(actual)
            .as("Verify SettlementBatch relationships")
            .satisfies(a -> assertThat(a.getExchange()).as("check exchange").isEqualTo(expected.getExchange()));
    }
}
