package com.rnexchange.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class TraderProfileAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTraderProfileAllPropertiesEquals(TraderProfile expected, TraderProfile actual) {
        assertTraderProfileAutoGeneratedPropertiesEquals(expected, actual);
        assertTraderProfileAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTraderProfileAllUpdatablePropertiesEquals(TraderProfile expected, TraderProfile actual) {
        assertTraderProfileUpdatableFieldsEquals(expected, actual);
        assertTraderProfileUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTraderProfileAutoGeneratedPropertiesEquals(TraderProfile expected, TraderProfile actual) {
        assertThat(actual)
            .as("Verify TraderProfile auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTraderProfileUpdatableFieldsEquals(TraderProfile expected, TraderProfile actual) {
        assertThat(actual)
            .as("Verify TraderProfile relevant properties")
            .satisfies(a -> assertThat(a.getDisplayName()).as("check displayName").isEqualTo(expected.getDisplayName()))
            .satisfies(a -> assertThat(a.getEmail()).as("check email").isEqualTo(expected.getEmail()))
            .satisfies(a -> assertThat(a.getMobile()).as("check mobile").isEqualTo(expected.getMobile()))
            .satisfies(a -> assertThat(a.getKycStatus()).as("check kycStatus").isEqualTo(expected.getKycStatus()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTraderProfileUpdatableRelationshipsEquals(TraderProfile expected, TraderProfile actual) {
        // empty method
    }
}
