package com.rnexchange.domain;

import static com.rnexchange.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class TradingAccountAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTradingAccountAllPropertiesEquals(TradingAccount expected, TradingAccount actual) {
        assertTradingAccountAutoGeneratedPropertiesEquals(expected, actual);
        assertTradingAccountAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTradingAccountAllUpdatablePropertiesEquals(TradingAccount expected, TradingAccount actual) {
        assertTradingAccountUpdatableFieldsEquals(expected, actual);
        assertTradingAccountUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTradingAccountAutoGeneratedPropertiesEquals(TradingAccount expected, TradingAccount actual) {
        assertThat(actual)
            .as("Verify TradingAccount auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTradingAccountUpdatableFieldsEquals(TradingAccount expected, TradingAccount actual) {
        assertThat(actual)
            .as("Verify TradingAccount relevant properties")
            .satisfies(a -> assertThat(a.getType()).as("check type").isEqualTo(expected.getType()))
            .satisfies(a -> assertThat(a.getBaseCcy()).as("check baseCcy").isEqualTo(expected.getBaseCcy()))
            .satisfies(a ->
                assertThat(a.getBalance()).as("check balance").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getBalance())
            )
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTradingAccountUpdatableRelationshipsEquals(TradingAccount expected, TradingAccount actual) {
        assertThat(actual)
            .as("Verify TradingAccount relationships")
            .satisfies(a -> assertThat(a.getBroker()).as("check broker").isEqualTo(expected.getBroker()))
            .satisfies(a -> assertThat(a.getTrader()).as("check trader").isEqualTo(expected.getTrader()));
    }
}
